### ISSUE TITLE
Pull request proposal for multiple improvements/features

### ISSUE THREAD

**Issue by johnny-bit** [woothemes/icons-for-features#11]
Hi!

Over last 2 weeks on requesty by my customer, I've added a lot of functionality into icons or features and updated couple things.

Please have a look at the code over at [hakger/icons-for-features](https://github.com/hakger/icons-for-features)

The changes amass to:

* Integrating PR #6 (fixing #2) and #10 (fixing #9)
* Throws out choosen script and select in favor of text field (fixes #3) since choosing from literally hundreds of icons in dropdown is pain + browsing for particular icon without search is much pain.
* Updated fontawesome to 4.4
* Throws out less/css files for fontawesome, as those are most probably not useful for plugin users
* Adds option to conditionally load fontawesome stylesheet on pages (for example if theme already loads FontAwesome, loading old Fontawesome again causes problems for displaying new icons and causes double download for new/old font files)
* Adds option for using FontAwesome from CDN
* Adds option for loadin stylesheet from different location (allows to load also something else than fontawesome)
* Adds options for conditional loading on admin pages (customer had plugin that added nice icons in admin dashboard and unconditional loading caused pain same as with loading on normal pages)
* Adds option to specify prefix for icon. This allows to either disable auto-prefixing (one customer used 2 different font icons with 2 diferent prefixes, so each time had to input them along icon name) or allow other prefixes (like using completedy different iconfont)

All options are added as admin page under "Features" post menu.

There are also some minor code fixes for some styling that bugged me, but noting major (except maybe removing everything from and avoid using `get_supported_icon_list` as this is hery hard to maintain)

My question: Would You guys be interested in merging those changes to upstream? Obviously it depends on PRs #10 and #6 to be merged beforehand. Also should I split changes into manageable multiple pull request or one big PR?

ps: Thanks for making this plugin! :smile:

**Comment by jeffikus** [comment]
All of the above listed issues/pull requests are closed/merged. Please reopen if there are any additional things you would like to see.

**Comment by johnny-bit** [comment]
Hi!

Far from all :wink:. More like : 
Integrating PR #6 (fixing #2) and #10 (fixing #9)

This is what I want to see (and done in PR #12):
- Throws out choosen script and select in favor of text field (fixes #3) since choosing from literally hundreds of icons in dropdown is pain + browsing for particular icon without search is much pain.

Reasoning behind this is not that choosen is bad itself, it's just multitude of problems with "select" approach: first of all - total dependency on FontAwesome, second - huge maintenance cost associated with FontAwesome updates (IMO `get_supported_icon_list` is just bad practice in general), moreover it creates (dumb but hey) problem where user cannot associate more than one class with icon (eg fa-spin+fa-cog) etc etc. 
- Updated fontawesome to 4.4

Reasoning: duh... Plus throwing out `get_supported_icon_list` means plugin code won't grow for 200+ unnecesary lines of icon names :wink:
- Throws out less/scss files for fontawesome, as those are most probably not useful for plugin users

Reasoning: Sass and less are used by theme devs... theme devs using those also (most probably) use stuff like bower, npm, grunt, gulp and/or loads more. Those files in plugin are unnecessary bloat. scss/less files for basic styling however are not thrown out, since theme author MAY think about including those in compiling theme stylesheet.. or actually use them as reference points :wink:
- Adds option to conditionally load fontawesome stylesheet on pages (for example if theme already loads FontAwesome, loading old Fontawesome again causes problems for displaying new icons and causes double download for new/old font files)

Reasoning given within point. Actually this was my beef with this plugin. I use not only newst font awesome, but sometimes specific icon font and fontawesome in that case would be unnecessary bloat.
- Adds option for using FontAwesome from CDN

Reasoning: CDNs are awesome. By using this from well-known cdn we have chance for hitting user cache and speeding customer site! yay!
- Adds option for loadin stylesheet from different location (allows to load also something else than fontawesome)

Reasoning: Plugin has outdated fontawesome? use this! Want to load something different (but it does not load itself) use this!
- Adds options for conditional loading on admin pages (customer had plugin that added nice icons in admin dashboard and unconditional loading caused pain same as with loading on normal pages)

Reasoning given within point. Took couple of tries to get right, but form in PR #12 is nice compromise.
- Adds option to specify prefix for icon. This allows to either disable auto-prefixing (one customer used 2 different font icons with 2 different prefixes, so each time had to input them along icon name) or allow other prefixes (like using completely different icon-font)

Reasoning given within point. Use fontawesome? Default is "fa", using other icon-font? set custom prefix. Using more that one (which is IMO weird) set to none, and have fun inputting those.
- All options are added as admin page under "Features" post menu.

So - Under " :star: Features" there's "Icons" page which is Options for Icons-for-Features. Neat? I just like when plugin has options close to what it does. No need to put it on admin.
- some minor code fixes for some styling that bugged me, but noting major (except maybe removing everything from and avoid using `get_supported_icon_list` as this is very hard to maintain)

`get_supported_icon_list` creates unnecessary burden on developer creating PRs for new FontAwesome and very unnecessary burden for users wanting to use something different than FontAwesome. One would actually have to circumvent this using oh-so-very-nice hooks. Instead throw it out.

So - we can discuss my points, I think they are sane and worthy of inclusion. I can obviously create PRs for each of those individually instead of #12
