### ISSUE TITLE
Text field option for inputting Font Awesome class

### ISSUE THREAD

**Issue by nickburne** [woothemes/icons-for-features#3]
Suggesting an enhancement:

I think it would be easier to add in the Font Awesome classes into a text field to save time. 

Maybe it's just me?

**Comment by johnny-bit** [comment]
Hi! With Choosen script, one can only choose among icons in very old Font Awesome. Text field IS better IMO. After all select with 585 options (all icons in FA 4.4) + goddless amount of alliases available would make select field incomprehensible.

**Comment by johnny-bit** [comment]
Hello,

My experience with Chosen script is overall positive, but not for my usecases (and for my customers usecases) with this plugin. This relies on `get_supported_icon_list` for list of available icons which creates unnecessary burden upon updating FontAwesome, prevents from using other icon-fonts without writting plugin to circumvent `get_supported_icon_list` with hook... see #11 for more info.
