### ISSUE TITLE
Clickable icons

### ISSUE THREAD

**Issue by mackaaij** [woothemes/icons-for-features#9]
Would be great if clicking an icons would open the link the title points to. Is that easy to add?

Also note there are two open questions in the support section of the plugin over at WordPress:
https://wordpress.org/support/plugin/icons-for-features

**Comment by jeffikus** [comment]
@danieldudzic would you like to submit a pull request for this one?

**Comment by danieldudzic** [comment]
@jeffikus Will do!

**Comment by jeffikus** [comment]
@danieldudzic ETA for doing this? I wanna update my planned release dates by end of today. thanks!

**Comment by danieldudzic** [comment]
@jeffikus I'll try to push this tonight.
